version: '3.9'

services:
  nextcloud:
    image: nextcloud
    container_name: devops-nextcloud
    volumes:
      - /home/pukito/nextcloud:/var/www/html
    ports:
      - "9090:80"
    networks:
      - nextcloud_network
    build:
      context: .
      dockerfile: Dockerfile

networks:
  nextcloud_network:
    driver: bridge
